on:
  pull_request:
    branches:
      - master

name: sample_actions

jobs:
  sample-job:
    runs-on: ubuntu-latest
    steps:
      - name: simple-step
        #run: echo "Action 1"
        run: echo "Action 2"

